# Generated by Django 4.0.3 on 2022-04-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_invoice_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceId',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
