# Generated by Django 4.0.3 on 2022-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_invoice_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
