# Generated by Django 4.0.3 on 2022-04-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_price_invoice_total_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(to='products.entry'),
        ),
    ]
