# Generated by Django 4.0.3 on 2022-04-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_remove_invoice_products_remove_invoice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='products.invoice'),
        ),
    ]
