# Generated by Django 4.0.3 on 2022-04-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cart_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Invoice_Cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
