# Generated by Django 4.0.3 on 2022-05-19 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_alter_invoice_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_title',
            field=models.CharField(default='ar', max_length=75, verbose_name='Arabic title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=75, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceId',
            field=models.CharField(blank=True, max_length=8, verbose_name='invoice ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=75, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='invoice_cart',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Title'),
        ),
    ]
