# Generated by Django 4.0.3 on 2022-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_ar_title_alter_category_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ar_title',
            field=models.CharField(db_index=True, default='arabic title', max_length=75, verbose_name='Arabic title'),
        ),
    ]
