# Generated by Django 4.0.3 on 2022-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_ar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default', upload_to='images'),
            preserve_default=False,
        ),
    ]
