# Generated by Django 4.0.3 on 2022-06-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card')], default='Credit', max_length=75, verbose_name='payment type'),
        ),
    ]
